# Generated by Django 4.0.6 on 2022-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Flivingstonbagel.com%2Fwp-content%2Fuploads%2F2016%2F11%2Ffood-placeholder.jpg&imgrefurl=https%3A%2F%2Fwww.everestkitchenpa.com%2Fassets%2Fpages%2Fdesserts.html&tbnid=Ag1_-7HSofts3M&vet=12ahUKEwiMpuGY__X7AhVkBkQIHb6nCW0QMygQegUIARDmAQ..i&docid=cZ2qdGfv-C1FKM&w=499&h=374&q=food%20placeholder%20image&ved=2ahUKEwiMpuGY__X7AhVkBkQIHb6nCW0QMygQegUIARDmAQ', max_length=600),
        ),
    ]
